import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { validateMp4, assertVideoUploadRequest, isVideoAspect, sameAspect, VideoRejectError, VIDEO_MESSAGES, type VideoRejectReason } from "./video-validate";

// Fixtures generated by __fixtures__/generate.sh (ffmpeg).
const fx = (name: string) => new Uint8Array(readFileSync(path.join(__dirname, "__fixtures__", name)));

async function reason(p: Promise<unknown>): Promise<VideoRejectReason | "OK"> {
  try {
    await p;
    return "OK";
  } catch (e) {
    if (e instanceof VideoRejectError) return e.reason;
    throw e;
  }
}

describe("validateMp4", () => {
  it("accepts a 1280x720 H.264 + AAC MP4 under the bitrate caps", async () => {
    const info = await validateMp4(fx("valid-720p.mp4"), { width: 1280, height: 720 });
    expect(info).toMatchObject({ width: 1280, height: 720, videoCodec: "avc", audioCodec: "aac" });
    expect(info.durationSeconds).toBeCloseTo(2, 1);
    expect(info.videoBitrate).toBeLessThanOrEqual(1_100_000);
    expect(info.audioBitrate).toBeLessThanOrEqual(140_800);
  });
  it("accepts a 720x1280 portrait MP4", async () => {
    const info = await validateMp4(fx("valid-portrait.mp4"), { width: 720, height: 1280 });
    expect([info.width, info.height]).toEqual([720, 1280]);
  });
  it("honors the rotation matrix (coded 1280x720, displayed 720x1280)", async () => {
    const info = await validateMp4(fx("rotated.mp4"), { width: 720, height: 1280 });
    expect([info.width, info.height]).toEqual([720, 1280]);
    expect(await reason(validateMp4(fx("rotated.mp4"), { width: 1280, height: 720 }))).toBe("VIDEO_DIMENSIONS_MISMATCH");
  });
  it("rejects when declared dimensions differ from the file", async () => {
    expect(await reason(validateMp4(fx("valid-720p.mp4"), { width: 1920, height: 1080 }))).toBe("VIDEO_DIMENSIONS_MISMATCH");
  });
  it("rejects video bitrate above 1 Mbps (+10%)", async () => {
    expect(await reason(validateMp4(fx("high-bitrate.mp4"), { width: 1280, height: 720 }))).toBe("VIDEO_BITRATE");
  });
  it("rejects audio bitrate above 128 kbps (+10%)", async () => {
    expect(await reason(validateMp4(fx("high-audio.mp4"), { width: 1280, height: 720 }))).toBe("AUDIO_BITRATE");
  });
  it("rejects frames that are not 1080p/720p 16:9 or 9:16", async () => {
    expect(await reason(validateMp4(fx("bad-frame.mp4"), { width: 1000, height: 1000 }))).toBe("VIDEO_FRAME");
  });
  it("rejects HEVC", async () => {
    expect(await reason(validateMp4(fx("hevc.mp4"), { width: 1280, height: 720 }))).toBe("VIDEO_CODEC");
  });
  it("rejects QuickTime containers", async () => {
    expect(await reason(validateMp4(fx("quicktime.mov"), { width: 1280, height: 720 }))).toBe("VIDEO_FORMAT");
  });
  it("rejects garbage and truncated files", async () => {
    expect(await reason(validateMp4(new TextEncoder().encode("<html>not a video</html>")))).toBe("VIDEO_FORMAT");
    const truncated = fx("valid-720p.mp4").subarray(0, 2000);
    expect(await reason(validateMp4(truncated, { width: 1280, height: 720 }))).not.toBe("OK");
  });
  it("rejects padding hidden outside the samples (whole-file bitrate)", async () => {
    const base = fx("valid-720p.mp4");
    // Append a 400 KB `free` box: samples stay the same, file grows beyond the cap for a 2 s clip.
    const pad = new Uint8Array(400 * 1024);
    new DataView(pad.buffer).setUint32(0, pad.length);
    pad.set(new TextEncoder().encode("free"), 4);
    const padded = new Uint8Array(base.length + pad.length);
    padded.set(base);
    padded.set(pad, base.length);
    expect(await reason(validateMp4(padded, { width: 1280, height: 720 }))).toBe("VIDEO_BITRATE");
  });
});

describe("assertVideoUploadRequest", () => {
  const ok = { mimeType: "video/mp4", sizeBytes: 1_000_000, width: 1280, height: 720, durationSeconds: 5 };
  const r = (x: Parameters<typeof assertVideoUploadRequest>[0]) => {
    try {
      assertVideoUploadRequest(x);
      return "OK";
    } catch (e) {
      return (e as VideoRejectError).reason;
    }
  };
  it("accepts the four allowed frames", () => {
    for (const [width, height] of [[1920, 1080], [1280, 720], [1080, 1920], [720, 1280]]) expect(r({ ...ok, width, height })).toBe("OK");
  });
  it("rejects non-MP4, bad frames, missing duration and > 10 MB", () => {
    expect(r({ ...ok, mimeType: "video/quicktime" })).toBe("VIDEO_FORMAT");
    expect(r({ ...ok, mimeType: "video/webm" })).toBe("VIDEO_FORMAT");
    expect(r({ ...ok, width: 1000, height: 1000 })).toBe("VIDEO_FRAME");
    expect(r({ ...ok, width: 1366, height: 768 })).toBe("VIDEO_FRAME");
    expect(r({ ...ok, width: undefined })).toBe("VIDEO_FRAME");
    expect(r({ ...ok, durationSeconds: 0 })).toBe("VIDEO_DURATION");
    expect(r({ ...ok, durationSeconds: undefined })).toBe("VIDEO_DURATION");
    expect(r({ ...ok, sizeBytes: 10 * 1024 * 1024 + 1 })).toBe("VIDEO_TOO_LARGE");
  });
  it("uses the product pt-BR messages", () => {
    expect(VIDEO_MESSAGES.VIDEO_FORMAT).toBe("Converta o vídeo para MP4 1080p ou 720p (16:9 ou 9:16) antes de enviar");
    expect(VIDEO_MESSAGES.VIDEO_TOO_LARGE).toBe("Vídeo acima de 10 MB após a conversão; envie um trecho mais curto (até ~70 s)");
  });
});

describe("aspect helpers", () => {
  it("isVideoAspect allows 16:9 / 9:16 within 2%", () => {
    expect(isVideoAspect(1280, 720)).toBe(true);
    expect(isVideoAspect(720, 1280)).toBe(true);
    expect(isVideoAspect(1000, 570)).toBe(true); // 1.754 ≈ -1.3%
    expect(isVideoAspect(1000, 1000)).toBe(false);
    expect(isVideoAspect(1600, 1000)).toBe(false); // 16:10
    expect(isVideoAspect(0, 720)).toBe(false);
  });
  it("sameAspect distinguishes landscape from portrait", () => {
    expect(sameAspect({ width: 1280, height: 720 }, { width: 1920, height: 1080 })).toBe(true);
    expect(sameAspect({ width: 720, height: 1280 }, { width: 1920, height: 1080 })).toBe(false);
  });
});
